apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: test-sensor
spec:
  dependencies:
    - name: test-dep
      eventSourceName: test-event
      eventName: example
  template:
    serviceAccountName: operate-workflows-sa
  triggers:
    - template:
        name: test
        argoWorkflow:
          operation: submit
          args:
            - "--node-field-selector"
            - "phase=abc"
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                namespace: argo
                name: build-crypto-l2-ingest-image
              spec:
                entrypoint: test
                templates:
                  - name: test
                    container:
                      image: docker/whalesay
                      command:
                        - cowsay
                      args : ["hello world"]
#        k8s:
#          operation: create
#          source:
#            resource:
#              apiVersion: argoproj.io/v1alpha1
#              kind: Workflow
#              metadata:
#                namespace: argo
#                name: build-crypto-l2-ingest-image
#              spec:
#                entrypoint: test
#                templates:
#                  - name: test
#                    container:
#                      image: docker/whalesay
#                      command:
#                        - cowsay
#                      args : ["hello world"]
