apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
#  namespace: argo
  name: build-crypto-l2-ingest-image
spec:
  entrypoint: test
  templates:
    - name: test
      container:
        image: docker/whalesay
        command:
          - cowsay
        args : ["hello world"]
