apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo
  project: infra
  source:
    repoURL: https://github.com/argoproj/argo-workflows.git
    path: manifests/quick-start/postgres
    targetRevision: v3.3.1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true