apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://github.com/argoproj/argo-workflows.git
    path: manifests/cluster-install
    targetRevision: v3.3.1