apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: git@github.com:argoproj/argo-workflows?rev=v3.3.1
    path: manifests/cluster-install