apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
  project: infra
  source:
    repoURL: https://github.com/argoproj/argo-events.git
    path: manifests/cluster-install
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-events