apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argocd-bootstrap
spec:
  destination:
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: git@github.com:Bouldersky/ops.git
    path: bootstrap